### ISSUE TITLE
Build broken 

### ISSUE THREAD

**Issue by naveenc-93** [xen-troops/meta-xt-prod-devel-rcar#104]
Hello Team,

I face below build errors while I build for H3 starter-kit.
NOTE: weston: Performing groupadd with [--root yocto/build-domd/tmp/work/h3ulcb-linux/agl-demo-platform/1.0-r0/rootfs --gid 986 --system weston-launch]
configuration error - unknown item 'SYSLOG_SU_ENAB' (notify administrator)
configuration error - unknown item 'SYSLOG_SG_ENAB' (notify administrator)
Running groupadd commands...
I have same similar errors while adding group ids for few recipes such as systemd-journal, systemd-coredump etc
could you please help me in resolving these issues?

**Comment by lorc** [comment]
It appears that we have broken AGL while we switched to kirkstone.

@rshym, what is your opinion?

@naveenc-93, it may be quick fix: https://stackoverflow.com/questions/73801394/yocto-kirkstone-systemd-create-users-issue-on-first-build

But, I am afraid that right now we may not support AGL builds at all... @rshym may clarify this.

**Comment by naveenc-93** [comment]
Hello @lorc,
Thank you for your reply. I had observed it do happen for non-agl builds as well. it looks like if we do add any features related to systemd, these errors are observed. 

```
configuration error - unknown item 'SYSLOG_SG_ENAB' (notify administrator)
Running groupadd commands...
NOTE: systemd: Performing groupadd with [--root yocto/build-domd/tmp/work/h3ulcb-agl-linux/agl-demo-platform/1.0-r0/rootfs --gid 989 --system systemd-journal]
configuration error - unknown item 'SYSLOG_SU_ENAB' (notify administrator)
configuration error - unknown item 'SYSLOG_SG_ENAB' (notify administrator)
NOTE: systemd: Performing groupadd with [--root yocto/build-domd/tmp/work/h3ulcb-agl-linux/agl-demo-platform/1.0-r0/rootfs  --gid 888 systemd-coredump]
configuration error - unknown item 'SYSLOG_SU_ENAB' (notify administrator)
configuration error - unknown item 'SYSLOG_SG_ENAB' (notify administrator)
NOTE: systemd: Performing groupadd with [--root yocto/build-domd/tmp/work/h3ulcb-agl-linux/agl-demo-platform/1.0-r0/rootfs  --gid 1005 systemd-network]
configuration error - unknown item 'SYSLOG_SU_ENAB' (notify administrator)
configuration error - unknown item 'SYSLOG_SG_ENAB' (notify administrator)
NOTE: systemd: Performing groupadd with [--root yocto/build-domd/tmp/work/h3ulcb-agl-linux/agl-demo-platform/1.0-r0/rootfs  --gid 982 polkitd]
NOTE: systemd: group polkitd already exists, not re-creating it
NOTE: systemd: Performing groupadd with [--root yocto/build-domd/tmp/work/h3ulcb-agl-linux/agl-demo-platform/1.0-r0/rootfs  --gid 1006 systemd-resolve]
```

In the above log, I could see these errors are appeared for systemd-* components. these errors also do happen at the time of "do_rootfs" of the image

**Comment by rshym** [comment]
Hello @naveenc-93,

As I understand, you build the product with AGL using `prod-devel-rcar-agl.yaml`

First, I want to mention, that this yaml-file needs some updates - it should use `dunfell` branch for `meta-xt-common` and `meta-xt-rcar`.

```
    - type: git
      url: "https://github.com/xen-troops/meta-xt-common.git"
      rev: dunfell
    - type: git
      url: "https://github.com/xen-troops/meta-xt-rcar.git"
      rev: dunfell
```

Unfortunately, I can't check this right now. But you may try to fix branches and check the results.
You need to re-run `moulin ...` after changes to yaml.

**Comment by naveenc-93** [comment]
Issue is resolved. There was a conflict of recipes where multiple recipes trying to install a file to same location.
